In [1]:
! pip install gym


[notice] A new release of pip is available: 23.2.1 -> 24.0
[notice] To update, run: C:\Users\HP\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip



     ---------------------------------------- 0.0/721.7 kB ? eta -:--:--
      --------------------------------------- 10.2/721.7 kB ? eta -:--:--
     - ----------------------------------- 30.7/721.7 kB 262.6 kB/s eta 0:00:03
     --- --------------------------------- 71.7/721.7 kB 438.9 kB/s eta 0:00:02
     --------- -------------------------- 194.6/721.7 kB 985.7 kB/s eta 0:00:01
     ---------------- --------------------- 317.4/721.7 kB 1.3 MB/s eta 0:00:01
     ----------------------- -------------- 450.6/721.7 kB 1.6 MB/s eta 0:00:01
     ----------------------------- -------- 563.2/721.7 kB 1.8 MB/s eta 0:00:01
     ----------------------------------- -- 665.6/721.7 kB 1.8 MB/s eta 0:00:01
     -------------------------------------- 721.7/721.7 kB 1.8 MB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'do

In [2]:
import gym

env = gym.make('MountainCar-v0')
num_episodes = 20

for i in range(num_episodes):
    t = 0
    observation = env.reset()  # Initialize observation
    while True:
        t += 1
        env.render()
        print(observation)  # Print the observation
        action = env.action_space.sample()
        step_result = env.step(env.action_space.sample())  # Take a random action
        print("Step result:", step_result)
        if len(step_result) > 4:
            print("Received unexpected extra values from env.step()")
        elif len(step_result) < 4:
            print("Received unexpected missing values from env.step()")
        observation, reward, done, _ = step_result[:4]  
        done=True
        if done:
            print("Episode finished after {} timesteps".format(t))
            break

env.close()


(array([-0.43062884,  0.        ], dtype=float32), {})
Step result: (array([-4.3031710e-01,  3.1173066e-04], dtype=float32), -1.0, False, False, {})
Received unexpected extra values from env.step()
Episode finished after 1 timesteps
(array([-0.5777299,  0.       ], dtype=float32), {})
Step result: (array([-5.7732564e-01,  4.0420116e-04], dtype=float32), -1.0, False, False, {})
Received unexpected extra values from env.step()
Episode finished after 1 timesteps
(array([-0.5788686,  0.       ], dtype=float32), {})
Step result: (array([-0.577456  ,  0.00141263], dtype=float32), -1.0, False, False, {})
Received unexpected extra values from env.step()
Episode finished after 1 timesteps
(array([-0.41164157,  0.        ], dtype=float32), {})
Step result: (array([-4.1146556e-01,  1.7601949e-04], dtype=float32), -1.0, False, False, {})
Received unexpected extra values from env.step()
Episode finished after 1 timesteps
(array([-0.41983327,  0.        ], dtype=float32), {})
Step result: (array([-4

C:\Users\HP\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\gym\envs\classic_control\mountain_car.py:171: UserWarning: WARN: You are calling render method without specifying any render mode. You can specify the render_mode at initialization, e.g. gym("MountainCar-v0", render_mode="rgb_array")
  gym.logger.warn(
C:\Users\HP\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\gym\utils\passive_env_checker.py:233: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
  if not isinstance(terminated, (bool, np.bool8)):
